#!/usr/bin/env groovy

pipeline {
  agent {
    label { label 'name-label-python' }
  }
  environment {
      WORKSPACE = '/usr/share/jenkins/workspace'
      PATH_SCRIPT = 'scripts/jenkins_saferestart'
      RUN_PYTHON = 'python3.7'
      RUN_PIP = 'pip3.7'
      SCRIPT = 'pipeline_jenkins_saferestart.py'
  }
  stages {
    stage ('Safe restart jenkins') {
        steps {
            withCredentials([string(credentialsId: 'JENKINS_KEYCLOAK_USER', variable: 'keycloak_user_env'), string(credentialsId: 'JENKINS_KEYCLOAK_PW', variable: 'keycloak_password_env'), string(credentialsId: 'CLIENT_ID_KEYCLOAK', variable: 'client_id_keycloak_env'), string(credentialsId: 'SECRET_KEYCLOAK', variable: 'secret_keycloak_env'), string(credentialsId: 'TOKEN_SRV_URL', variable: 'token_srv_url_env'), string(credentialsId: 'KEYCLOAK_REALM', variable: 'keycloak_realm_env')]) 
            {
                sh 'PATH="./:$PATH" $RUN_PYTHON $WORKSPACE/$JOB_NAME/$PATH_SCRIPT/$SCRIPT --jenkins_url=$jenkins_url_env --jenkins_domain=$jenkins_domain_env --keycloak_user=$keycloak_user_env --keycloak_password=$keycloak_password_env --client_id_keycloak=$client_id_keycloak_env --secret_keycloak=$secret_keycloak_env --keycloak_realm=$keycloak_realm_env --token_srv_url=$token_srv_url_env --jenkins_running_list="$jenkins_running_list_env"'
            }
        }
    }
  }
}